### ISSUE TITLE
Sitecore Marketplace page is out of date

### ISSUE THREAD

**Issue by arencambre** [unic/SitecoreErrorManager#11]
https://marketplace.sitecore.net/en/Modules/Sitecore_Error_Manager.aspx says that the latest update of this module is from 2015, but it is clear per the checkins that there are many edits since then. Can you update the Marketplace page?

**Comment by retohugi** [comment]
Hey Aren, thanks for the heads up. I updated the marketplace and hope the change will be accepted soon. TBH, I tried to edit the marketplace entry a view times over the last years. And I usually gave up because the site either did not respond, I was not able to log in or I simply was not willing to bring up the patience to wait for the editor to load... Well, now I did it! (achievement unlocked) :rocket:

**Comment by retohugi** [comment]
Updated content approved and now live.

**Comment by arencambre** [comment]
Thank you for the update!
