### ISSUE TITLE
User not logged in on errors pages

### ISSUE THREAD

**Issue by an-kir** [unic/SitecoreErrorManager#9]
Hi!

When i get custom errors pages in UI (for example, Not Found page or Access Denied page), user is not logged in. Do you know how to fix this?

Thanks!

**Comment by aquasonic** [comment]
This can be fixed with the settings `ErrorManager.SendClientCookies`. When you set this to `true`, then client cookies will be send with the request and the user should be logged in.

See also [your question on Stack Overflow](http://stackoverflow.com/questions/33669302/sitecore-errormanager-module-user-not-logged-in-on-errors-pages).

Does this solve your issue?

Thanks and regards,
Kevin

**Comment by an-kir** [comment]
Yes, it helped. Thank you
